DROP TABLE IF EXISTS "accounts";
DROP TABLE IF EXISTS "users";
DROP TABLE IF EXISTS "transactions";

CREATE TABLE IF NOT EXISTS "users" (
    "ID" BIGINT AUTO_INCREMENT PRIMARY KEY,
    "USERNAME" VARCHAR(255) UNIQUE NOT NULL,
    "PASSWORD" VARCHAR(255) NOT NULL,
    "ROLE" VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS "accounts" (
    "ID" BIGINT AUTO_INCREMENT PRIMARY KEY,
    "ACCOUNT_NUMBER" VARCHAR(255) UNIQUE NOT NULL,
    "BALANCE" DECIMAL(19, 2) NOT NULL DEFAULT 0.00,
    "ACCOUNT_TYPE" VARCHAR(50) NOT NULL,
    "user_id" BIGINT UNIQUE NOT NULL,
    CONSTRAINT "fk_user_accounts" FOREIGN KEY ("user_id") REFERENCES "users"("ID")
);

CREATE TABLE IF NOT EXISTS "transactions" (
    "ID" BIGINT AUTO_INCREMENT PRIMARY KEY,
    "SENDING_ACCOUNT_ID" VARCHAR(255) NOT NULL,
    "RECEIVING_ACCOUNT_ID" VARCHAR(255) NOT NULL,
    "TRANSFER_AMOUNT" DECIMAL(19, 2) NOT NULL,
    "LOCAL_DATE_TIME" TIMESTAMP NOT NULL,
    "user_id" BIGINT NOT NULL,
    CONSTRAINT "fk_user_transactions" FOREIGN KEY ("user_id") REFERENCES "users"("ID")
)