DROP TABLE IF EXISTS "accounts";
DROP TABLE IF EXISTS "users";

CREATE TABLE IF NOT EXISTS "users" (
    "ID" BIGINT AUTO_INCREMENT PRIMARY KEY,
    "USERNAME" VARCHAR(255) UNIQUE NOT NULL,
    "PASSWORD" VARCHAR(255) NOT NULL,
    "ROLE" VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS "accounts" (
    "ID" BIGINT AUTO_INCREMENT PRIMARY KEY,
    "ACCOUNT_NUMBER" VARCHAR(255) UNIQUE NOT NULL,
    "BALANCE" DECIMAL(19, 2) NOT NULL DEFAULT 0.00,
    "ACCOUNT_TYPE" VARCHAR(50) NOT NULL,
    "user_id" BIGINT UNIQUE NOT NULL,
    CONSTRAINT "fk_user" FOREIGN KEY ("user_id") REFERENCES "users"("ID")
);